//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyResponse
    {
        public int CompanyID { get; set; }
        public int ResumeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Resume Resume { get; set; }
    }
}
