//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyResponse = new HashSet<CompanyResponse>();
            this.Vacancy = new HashSet<Vacancy>();
        }
    
        public int ID { get; set; }
        public int LoginID { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string ShowName { get; set; }
        public int CompanyTypeID { get; set; }
        public string WebSite { get; set; }
        public int CompanySizeID { get; set; }
        public string City { get; set; }
        public string ContactName { get; set; }
        public string ContactSurname { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
    
        public virtual CompanySize CompanySize { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual Logins Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyResponse> CompanyResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancy> Vacancy { get; set; }
    }
}
