//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeResponse
    {
        public int EmployeeID { get; set; }
        public int VacancyID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
